app/routes/college.py
from flask import Blueprint, flash
from app.model.college_model import query_database, submit_form, edit_form, delete_form, search_form
from app.wtform.form import CollegeForm
from flask import render_template, request, redirect#, jsonify, url_for
#from flask import current_app as app

college_bp = Blueprint(
    "college_bp",
    __name__,
)

@college_bp.route('/')
def college():
    data = query_database()

    # Print the data for debugging purposes
    print("Data from query:", data)

    form = CollegeForm()
    return render_template('table/college.html', data=data, form=form)

@college_bp.route('/add', methods=['POST'])
def add():
    if request.method == 'POST':
        try:
            # Call the insert function in college_model
            submit_form()

            # Flash a success message
            # flash('Added successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Add failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@college_bp.route('/update', methods=['POST'])
def update():
    if request.method == 'POST':
        try:
            # Call the update function in college_model
            edit_form()

            # Flash a success message
            # flash('Updated successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Update failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@college_bp.route('/delete', methods=['POST'])
def delete():
    if request.method == 'POST':
        try:
            # Call the delete function in college_model
            delete_form()

            # Flash a success message
            # flash('Deleted successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Delete failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@college_bp.route('/search', methods=['POST'])
def search():
    search_query = request.form.get('search-query', '').lower()

    print(f"Received search query: {search_query} for table tblcollege")

    # Perform search logic based on the query
    search_results = search_form(search_query)

    #print(search_results)
    print(f"Final search results: {search_results}")
    
    return render_template('form/search/college-fs.html', results=search_results, form=CollegeForm())

app/routes/course.py
from flask import Blueprint, flash
from app.model.course_model import query_database, submit_form, edit_form, delete_form, search_form
from app.wtform.form import CourseForm
from flask import render_template, request, redirect#, jsonify, url_for

course_bp = Blueprint(
    "course_bp",
    __name__,
)

@course_bp.route('/')
def course():
    data = query_database()

    # Print the data for debugging purposes
    print("Data from query:", data)

    form = CourseForm()
    return render_template('table/course.html', data=data, form=form)

@course_bp.route('/add', methods=['POST'])
def add():
    if request.method == 'POST':
        try:
            # Call the insert function in course_model
            submit_form()

            # Flash a success message
            # flash('Added successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Add failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@course_bp.route('/update', methods=['POST'])
def update():
    if request.method == 'POST':
        try:
            # Call the update function in course_model
            edit_form()

            # Flash a success message
            # flash('Updated successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Update failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@course_bp.route('/delete', methods=['POST'])
def delete():
    if request.method == 'POST':
        try:
            # Call the delete function in course_model
            delete_form()

            # Flash a success message
            # flash('Deleted successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Delete failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@course_bp.route('/search', methods=['POST'])
def search():
    search_query = request.form.get('search-query', '').lower()

    print(f"Received search query: {search_query} for table tblcourse")

    # Perform search logic based on the query
    search_results = search_form(search_query)

    #print(search_results)
    print(f"Final search results: {search_results}")
    
    return render_template('form/search/course-fs.html', results=search_results, form=CourseForm())

app/routes/student.py
from flask import Blueprint, flash
from app.model.student_model import query_database, submit_form, edit_form, delete_form, search_form
from app.model.course_model import query_database as query_course
from app.wtform.form import StudentForm
from flask import render_template, request, redirect
import re

from cloudinary.uploader import upload, destroy
from app.model.util import public_id

student_bp = Blueprint(
    "student_bp",
    __name__,
)

@student_bp.route('/')
def student():
    data = query_database()

    # Print the data for debugging purposes
    print("Data from query:", data)

    form = StudentForm()
    courses = query_course() #get courses available in course table
    return render_template('table/student.html', data=data, form=form, courses=courses)

@student_bp.route('/add', methods=['POST'])
def add():
    if request.method == 'POST':
        id = request.form['id']
        photo = request.files['photo']
        #Check if ID correct format
        if not re.match(r'\d{4}-\d{4}', id):
            flash("Incorrect format.", 'danger')
            return redirect(request.referrer)
        try:
            if photo:
                upload_result = upload(photo, folder="ssis", resource_type='image')
                secure_url = upload_result['secure_url']
            else:
                secure_url = None
            # Call the insert function in student_model
            submit_form(secure_url)

            # Flash a success message
            # flash('Added successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Add failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

from flask import make_response

@student_bp.route('/update', methods=['POST'])
def update():
    if request.method == 'POST':
        currentPhoto = request.form.get('currentStudentPhotoUrl')
        newPhoto = request.files['studentPhoto']
        
        print("Current Photo: ",currentPhoto)
        print("New Photo :",newPhoto)
        try:
            # Upload new photo to cloudinary
            if newPhoto:
                upload_result = upload(newPhoto, folder="ssis", resource_type='image')
                secure_url = upload_result['secure_url']

                # flash(f"Uploaded new photo: {secure_url}", 'info')
                # Delete old photo from cloudinary
                if currentPhoto:
                    try:
                        # Extract public ID from the photo URL
                        public_id_val = public_id(currentPhoto)

                        # Delete the photo using its public ID
                        result = destroy("ssis/" + public_id_val)

                        # Check the deletion result
                        # if result.get("result") == "ok":
                        #     # Flash a success message
                        #     # flash('Updated successfully!', 'success')
                        # else:
                        #     # Flash an error message
                        #     flash(f"Error deleting old photo: {result.get('result')}", 'danger')
                    except Exception as e:
                        flash(f"Error deleting old photo: {str(e)}", 'danger')

                    # Call the update function in student_model
                    edit_form(secure_url)
                else:
                    # Call the update function in student_model
                    edit_form(secure_url)
                    # Flash a success message
                    # flash('Updated successfully!', 'success')
            else:
                secure_url = None

                # Call the update function in student_model
                edit_form(secure_url)
                # Flash a success message
                # flash('Updated successfully! No new photo.', 'success')

        except Exception as e:
            # Flash an error message
            flash(f'Update failed: {str(e)}', 'danger')
    
    # return jsonify({'success': False, 'error': 'Invalid request. Missing required data.'})
    return redirect(request.referrer)

@student_bp.route('/delete', methods=['POST'])
def delete():
    if request.method == 'POST':
        # Retrieve photo url
        photo = request.form.get('photoUrl')
        print("Photo: ",photo)
        try:
            # Delete old photo from cloudinary
            if photo:
                try:
                    # Extract public ID from the photo URL
                    public_id_val = public_id(photo)

                    # Delete the photo using its public ID
                    result = destroy("ssis/" + public_id_val)

                    # Check the deletion result
                    # if result.get("result") == "ok":
                    #     # Flash a success message
                    #     flash('Updated successfully!', 'success')
                    # else:
                    #     # Flash an error message
                    #     flash(f"Error deleting old photo: {result.get('result')}", 'danger')
                except Exception as e:
                    flash(f"Error deleting old photo: {str(e)}", 'danger')

                # Call the delete function in student_model
                delete_form()
            else:
                # Call the delete function in student_model
                delete_form()
                # Flash a success message
                # flash('Deleted successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Delete failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@student_bp.route('/search', methods=['POST'])
def search():
    search_query = request.form.get('search-query', '').lower()

    print(f"Received search query: {search_query} for table tblstudent")

    # Perform search logic based on the query
    search_results = search_form(search_query)

    #print(search_results)
    print(f"Final search results: {search_results}")
    
    return render_template('form/search/student-fs.html', results=search_results, form=StudentForm())

app/templates/form/edit/college-fe.html
<div class="card ml-2 mr-2">
    <div class="card-body"> 
        <form method="POST" action="{{ url_for('college_bp.update') }}">
            {{ form.hidden_tag() }}

            <div class="mb-3 ml-2 mr-2">
                <label for="{{ form.college.name }}" class="form-label">College:</label>
                <input type="text" id="collegeName" name="collegeName" class="form-control" required>
                <!-- Add a hidden input for the college code -->
                <input type="hidden" id="collegeCode" name="collegeCode">
            </div>

            <div class="d-flex justify-content-end">
                <button type="update" class="btn btn-primary mr-2"><i class="fa fa-paper-plane-o"></i> | Update</button>
            </div>
            
        </form>
    </div>
</div>

app/templates/form/edit/course-fe.html
<div class="card ml-2 mr-2">
    <div class="card-body"> 
        <form method="POST" action="{{ url_for('course_bp.update') }}">
            {{ form.hidden_tag() }}

            <div class="mb-3 ml-2 mr-2">
                <label for="{{ form.college.id }}" class="form-label">College:</label>
                <select class="form-select" id="courseCollege" name="courseCollege" required>
                    <option value="" selected disabled>--- Select College ---</option>
                    <option value="COE">COE</option>
                    <option value="CASS">CASS</option>
                    <option value="CEBA">CEBA</option>
                    <option value="CED">CED</option>
                    <option value="CHS">CHS</option>
                    <option value="CSM">CSM</option>
                    <option value="CCS">CCS</option>
                </select>
            </div>
    
            <div class="mb-3 ml-2 mr-2">
                <label for="{{ form.course.id }}" class="form-label">Course:</label>
                <input type="text" id="courseName" name="courseName" class="form-control" required>
                <!-- Add hidden input for course code -->
                <input type="hidden" id="courseCode" name="courseCode">
            </div>

            <div class="d-flex justify-content-end">
                <button type="update" class="btn btn-primary mr-2"><i class="fa fa-paper-plane-o"></i> | Update</button>
            </div>
            
        </form>
    </div>
</div>

app/templates/form/edit/student-fe.html
<div class="card ml-2 mr-2">
    <div class="card-body"> 
        <form method="POST" action="{{ url_for('student_bp.update') }}" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
    
            <div class="mb-3 ml-2 mr-2">
                <label for="{{ form.firstname.id }}" class="form-label">First Name:</label>
                <input type="text" id="studentFirstname" name="studentFirstname" class="form-control" required>

                <!-- Add hidden input for student id -->
                <input type="hidden" id="studentId" name="studentId">
            </div>
    
            <div class="mb-3 ml-2 mr-2">
                <label for="{{ form.lastname.id }}" class="form-label">Last Name:</label>
                <input type="text" id="studentLastname" name="studentLastname" class="form-control" required>
            </div>
    
            <div class="mb-3 ml-2 mr-2">
                <label for="{{ form.gender.id }}" class="form-label">Gender:</label>
                <select class="form-select" id="studentGender" name="studentGender" required>
                    <option value="" selected disabled>--- Select Gender ---</option>
                    <option value="F">Female</option>
                    <option value="M">Male</option>
                    <option value="Other">Other</option>
                    <option value="Prefer not to say">Prefer not to say</option>
                </select>
            </div>
    
            <div class="mb-3 ml-2 mr-2">
                <label for="{{ form.course.id }}" class="form-label">Course:</label>
                <select class="form-select" id="studentCourse" name="studentCourse" required>
                    <option value="" selected disabled>--- Select Course ---</option>
                    {% for course in courses %}
                        <option value="{{ course.code }}">{{ course.name }}</option>
                    {% endfor %}
                </select>
            </div>
    
            <div class="mb-3 ml-2 mr-2">
                <label for="{{ form.year.id }}" class="form-label">Year:</label>
                <select class="form-select" id="studentYear" name="studentYear" required>
                    <option value="" selected disabled>--- Select Year ---</option>
                    <option value="1">1st Year</option>
                    <option value="2">2nd Year</option>
                    <option value="3">3rd Year</option>
                    <option value="4">4th Year</option>
                </select>
            </div>
            
            <div class="mb-3 ml-2 mr-2">
                <label for="{{ form.photo.id }}" class="form-label">Current Picture:</label>
                <img id="currentStudentPhoto" class="img-fluid" alt="Current Student Photo">
                <input type="hidden" id="currentStudentPhotoUrl" name="currentStudentPhotoUrl">
            </div>

            <div class="mb-3 ml-2 mr-2">
                <label for="{{ form.photo.id }}" class="form-label">Update Picture:</label>
                <input type="file" id="studentPhoto" name="studentPhoto" class="form-control" accept="image/*"></input>
            </div>

            <div class="d-flex justify-content-end">
                <button type="update" class="btn btn-primary mr-2"><i class="fa fa-paper-plane-o"></i> | Update</button>
            </div>
        </form>
    </div>
</div>

<script>
    $(document).ready(function () {
    $('#studentPhoto').change(function () {
        var maxFileSize = 1024 * 1024; // 1 MB
        var fileSize = this.files[0].size;

        if (fileSize > maxFileSize) {
            alert('File size must be no more than 1 MB.');
            // Optionally, clear the file input
            $(this).val('');
        }


        var fileInput = document.getElementById('studentPhoto');

        // Check if any file is selected
        if (fileInput.files.length > 0) {
            // Get the selected file
            var selectedFile = fileInput.files[0];

            // Check the file type
            if (selectedFile.type.startsWith('image/')) {
                // It's a valid image type
                console.log('Valid image type!');
            } else {
                // It's not a valid image type
                alert('Please select a valid image file.');
                // You can optionally clear the file input to prevent submitting the invalid file
                fileInput.value = '';
            }
        }
    });
});
</script>