app/routes/college.py
from flask import Blueprint, flash
from app.model.college_model import query_database, submit_form, edit_form, delete_form, search_form
from app.wtform.form import CollegeForm
from flask import render_template, request, redirect#, jsonify, url_for
#from flask import current_app as app

college_bp = Blueprint(
    "college_bp",
    __name__,
)

@college_bp.route('/')
def college():
    data = query_database()

    # Print the data for debugging purposes
    print("Data from query:", data)

    form = CollegeForm()
    return render_template('table/college.html', data=data, form=form)

@college_bp.route('/add', methods=['POST'])
def add():
    if request.method == 'POST':
        try:
            # Call the insert function in college_model
            submit_form()

            # Flash a success message
            # flash('Added successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Add failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@college_bp.route('/update', methods=['POST'])
def update():
    if request.method == 'POST':
        try:
            # Call the update function in college_model
            edit_form()

            # Flash a success message
            # flash('Updated successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Update failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@college_bp.route('/delete', methods=['POST'])
def delete():
    if request.method == 'POST':
        try:
            # Call the delete function in college_model
            delete_form()

            # Flash a success message
            # flash('Deleted successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Delete failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@college_bp.route('/search', methods=['POST'])
def search():
    search_query = request.form.get('search-query', '').lower()

    print(f"Received search query: {search_query} for table tblcollege")

    # Perform search logic based on the query
    search_results = search_form(search_query)

    #print(search_results)
    print(f"Final search results: {search_results}")
    
    return render_template('form/search/college-fs.html', results=search_results, form=CollegeForm())

app/routes/course.py
from flask import Blueprint, flash
from app.model.course_model import query_database, submit_form, edit_form, delete_form, search_form
from app.wtform.form import CourseForm
from flask import render_template, request, redirect#, jsonify, url_for

course_bp = Blueprint(
    "course_bp",
    __name__,
)

@course_bp.route('/')
def course():
    data = query_database()

    # Print the data for debugging purposes
    print("Data from query:", data)

    form = CourseForm()
    return render_template('table/course.html', data=data, form=form)

@course_bp.route('/add', methods=['POST'])
def add():
    if request.method == 'POST':
        try:
            # Call the insert function in course_model
            submit_form()

            # Flash a success message
            # flash('Added successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Add failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@course_bp.route('/update', methods=['POST'])
def update():
    if request.method == 'POST':
        try:
            # Call the update function in course_model
            edit_form()

            # Flash a success message
            # flash('Updated successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Update failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@course_bp.route('/delete', methods=['POST'])
def delete():
    if request.method == 'POST':
        try:
            # Call the delete function in course_model
            delete_form()

            # Flash a success message
            # flash('Deleted successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Delete failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@course_bp.route('/search', methods=['POST'])
def search():
    search_query = request.form.get('search-query', '').lower()

    print(f"Received search query: {search_query} for table tblcourse")

    # Perform search logic based on the query
    search_results = search_form(search_query)

    #print(search_results)
    print(f"Final search results: {search_results}")
    
    return render_template('form/search/course-fs.html', results=search_results, form=CourseForm())

app/routes/student.py
from flask import Blueprint, flash
from app.model.student_model import query_database, submit_form, edit_form, delete_form, search_form
from app.model.course_model import query_database as query_course
from app.wtform.form import StudentForm
from flask import render_template, request, redirect
import re

from cloudinary.uploader import upload, destroy
from app.model.util import public_id

student_bp = Blueprint(
    "student_bp",
    __name__,
)

@student_bp.route('/')
def student():
    data = query_database()

    # Print the data for debugging purposes
    print("Data from query:", data)

    form = StudentForm()
    courses = query_course() #get courses available in course table
    return render_template('table/student.html', data=data, form=form, courses=courses)

@student_bp.route('/add', methods=['POST'])
def add():
    if request.method == 'POST':
        id = request.form['id']
        photo = request.files['photo']
        #Check if ID correct format
        if not re.match(r'\d{4}-\d{4}', id):
            flash("Incorrect format.", 'danger')
            return redirect(request.referrer)
        try:
            if photo:
                upload_result = upload(photo, folder="ssis", resource_type='image')
                secure_url = upload_result['secure_url']
            else:
                secure_url = None
            # Call the insert function in student_model
            submit_form(secure_url)

            # Flash a success message
            # flash('Added successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Add failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

from flask import make_response

@student_bp.route('/update', methods=['POST'])
def update():
    if request.method == 'POST':
        currentPhoto = request.form.get('currentStudentPhotoUrl')
        newPhoto = request.files['studentPhoto']
        
        print("Current Photo: ",currentPhoto)
        print("New Photo :",newPhoto)
        try:
            # Upload new photo to cloudinary
            if newPhoto:
                upload_result = upload(newPhoto, folder="ssis", resource_type='image')
                secure_url = upload_result['secure_url']

                # flash(f"Uploaded new photo: {secure_url}", 'info')
                # Delete old photo from cloudinary
                if currentPhoto:
                    try:
                        # Extract public ID from the photo URL
                        public_id_val = public_id(currentPhoto)

                        # Delete the photo using its public ID
                        result = destroy("ssis/" + public_id_val)

                        # Check the deletion result
                        # if result.get("result") == "ok":
                        #     # Flash a success message
                        #     # flash('Updated successfully!', 'success')
                        # else:
                        #     # Flash an error message
                        #     flash(f"Error deleting old photo: {result.get('result')}", 'danger')
                    except Exception as e:
                        flash(f"Error deleting old photo: {str(e)}", 'danger')

                    # Call the update function in student_model
                    edit_form(secure_url)
                else:
                    # Call the update function in student_model
                    edit_form(secure_url)
                    # Flash a success message
                    # flash('Updated successfully!', 'success')
            else:
                secure_url = None

                # Call the update function in student_model
                edit_form(secure_url)
                # Flash a success message
                # flash('Updated successfully! No new photo.', 'success')

        except Exception as e:
            # Flash an error message
            flash(f'Update failed: {str(e)}', 'danger')
    
    # return jsonify({'success': False, 'error': 'Invalid request. Missing required data.'})
    return redirect(request.referrer)

@student_bp.route('/delete', methods=['POST'])
def delete():
    if request.method == 'POST':
        # Retrieve photo url
        photo = request.form.get('photoUrl')
        print("Photo: ",photo)
        try:
            # Delete old photo from cloudinary
            if photo:
                try:
                    # Extract public ID from the photo URL
                    public_id_val = public_id(photo)

                    # Delete the photo using its public ID
                    result = destroy("ssis/" + public_id_val)

                    # Check the deletion result
                    # if result.get("result") == "ok":
                    #     # Flash a success message
                    #     flash('Updated successfully!', 'success')
                    # else:
                    #     # Flash an error message
                    #     flash(f"Error deleting old photo: {result.get('result')}", 'danger')
                except Exception as e:
                    flash(f"Error deleting old photo: {str(e)}", 'danger')

                # Call the delete function in student_model
                delete_form()
            else:
                # Call the delete function in student_model
                delete_form()
                # Flash a success message
                # flash('Deleted successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Delete failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@student_bp.route('/search', methods=['POST'])
def search():
    search_query = request.form.get('search-query', '').lower()

    print(f"Received search query: {search_query} for table tblstudent")

    # Perform search logic based on the query
    search_results = search_form(search_query)

    #print(search_results)
    print(f"Final search results: {search_results}")
    
    return render_template('form/search/student-fs.html', results=search_results, form=StudentForm())

app/templates/table/college.html
{% extends "layout.html" %}
{% block content %}
<br>

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}" role="alert">
            {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    {% endif %}
{% endwith %}
<br>
<h2 class="ml-2 mr-2 mb-3 d-flex justify-content-between align-items-center">College Information
    <div class="mr-2 d-flex justify-content-end">
        <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#collegeModal">
            <i class="fa fa-plus"></i> Add College
        </button>
    </div>
</h2>

<div class="card ml-2 mr-2">
    <form class="mb-2 d-flex">
        <input id="searchInput" class="form-control me-2 mr-1" type="search" placeholder="Search" aria-label="Search">
        <button id="searchButton" class="btn btn-outline-dark search-btn" data-table-id="tblcollege"><i class="fa fa-search"></i></button>
    </form>
    <div class="card-body table-responsive" style="height:40rem; overflow:auto;">
        <table id="tblcollege" class="table table-hover" style="text-align: center;">
            <thead class="table-secondary">
                <tr style="font-family: sans-serif;">
                    <th>Code</th>
                    <th>Name</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="college_tbody">
                {% for college in data %}
                    <tr>
                        <td>{{ college.code }}</td>
                        <td>{{ college.name }}</td>
                        <td>
                            <button class="btn btn-warning edit-btn" data-bs-toggle="modal" data-bs-target="#collegeEditModal" data-college-code="{{ college.code }}" data-college-name="{{ college.name }}"><i class="fa fa-pencil"></i> | Edit</button>
                            <button class="btn btn-danger delete-btn" data-college-code="{{ college.code }}"><i class="fa fa-trash"></i> | Delete</button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<br>

<script>
    var deleteUrl = "{{ url_for('college_bp.delete') }}";
    var searchUrl = "{{ url_for('college_bp.search') }}";
    var csrfToken = "{{ csrf_token() }}";
</script>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="{{ url_for('static', filename='js/college.js') }}"></script>

<!-- College Modal here -->
{% include 'modal/add/college-m.html' %}
{% include 'modal/edit/college-me.html' %}

{% endblock %}

app/templates/table/course.html
{% extends "layout.html" %}
{% block content %}

<br>
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}" role="alert">
            {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    {% endif %}
{% endwith %}
<br>
<h2 class="ml-2 mr-2 mb-3 d-flex justify-content-between align-items-center">Course Information
    <div class="mr-2 d-flex justify-content-end">
        <button type="button" class="btn btn-success" style="border: none;" data-bs-toggle="modal" data-bs-target="#courseModal">
            <i class="fa fa-plus"></i>  Add Course
        </button>
    </div>
</h2>

<div class="card ml-2 mr-2">
    <form class="mb-2 d-flex">
        <input id="searchInput" class="form-control me-2 mr-1" type="search" placeholder="Search" aria-label="Search">
        <button id="searchButton" class="btn btn-outline-dark search-btn"  data-table-id="tblcourse"><i class="fa fa-search"></i></button>
    </form>
    <div class="card-body table-responsive" style="height:40rem; overflow:auto;">
        <table id="tblcourse" class="table table-hover" style="text-align: center;">
            <thead class="table-secondary">
                <tr style="font-family: sans-serif;">
                    <th>Code</th>
                    <th>Name</th>
                    <th>College</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="course_tbody">
                {% for course in data %}
                    <tr>
                        <td>{{ course.code }}</td>
                        <td>{{ course.name }}</td>
                        <td>{{ course.college }}</td>
                        <td>
                            <button class="btn btn-warning edit-btn" data-bs-toggle="modal" data-bs-target="#courseEditModal"
                            data-course-code="{{ course.code }}" data-course-name="{{ course.name }}"
                            data-course-college="{{ course.college }}"><i class="fa fa-pencil"></i> | Edit</button>
                            <button class="btn btn-danger delete-btn" data-course-code="{{ course.code }}"><i class="fa fa-trash"></i> | Delete</button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


<script>
    var deleteUrl = "{{ url_for('course_bp.delete') }}";
    var searchUrl = "{{ url_for('course_bp.search') }}";
    var csrfToken = "{{ csrf_token() }}";
</script>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="{{ url_for('static', filename='js/course.js') }}"></script>

<!-- Course Modal here -->
{% include 'modal/add/course-m.html' %}
{% include 'modal/edit/course-me.html' %}

{% endblock %}

app/templates/table/student.html
<section>
    {% extends "layout.html" %}
    {% block content %}

    <br>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}" role="alert">
            {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    {% endif %}
    {% endwith %}

    <br>
    <h2 class="ml-2 mr-2 mb-3 d-flex justify-content-between align-items-center">Student Information
        <div class="mr-2 d-flex justify-content-end">
            <button type="button" class="btn btn-success" style="border: none;" data-bs-toggle="modal" data-bs-target="#studentModal">
                <i class="fa fa-plus"></i>  Add Student
            </button>
        </div>
    </h2>
    

    <div class="card ml-2 mr-2">
        <form id="searchForm" class="mb-2 d-flex">
            <input id="searchInput" class="form-control me-2 mr-1" type="search" placeholder="Search" aria-label="Search">
            <button id="searchButton" class="btn btn-outline-dark search-btn" data-table-id="tblstudent"><i class="fa fa-search"></i></button>
        </form>
        <div class="card-body table-responsive" style="height:40rem; overflow:auto;">
            <table id="tblstudent" class="table table-hover" style="text-align: center;">
                <thead class="table-secondary">
                    <tr style="font-family: sans-serif;">
                        <th>Profile Picture</th>
                        <th>ID</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Course</th>
                        <th>College Name</th>
                        <th>Year</th>
                        <th>Gender</th>
                        <th>Picture</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody id="student_tbody">
                    {% if data %}
                        {% for student in data %}
                            <tr>
                                <td>
                                    {% if student.photoUrl %}
                                    <img src="{{ student.photoUrl }}" class="img-fluid" width="80" height="80">
                                    {% else %}
                                    <img src="https://t4.ftcdn.net/jpg/04/73/25/49/360_F_473254957_bxG9yf4ly7OBO5I0O5KABlN930GwaMQz.jpg" class="img-fluid" width="80" height="80">
                                    {% endif %}
                                </td>
                                <td>{{ student.id }}</td>
                                <td>{{ student.firstName }}</td>
                                <td>{{ student.lastName }}</td>
                                <td>{{ student.course }}</td>
                                <td>{{ student.college_name }}</td>
                                <td>{{ student.year }}</td>
                                <td>{{ student.gender }}</td>
                                <td>
                                    <button class="btn btn-primary photo-btn" data-bs-toggle="modal" data-bs-target="#studentPhotoModal"
                                        data-student-photo="{{ student.photoUrl }}"> 
                                        <i class="fa fa-eye"> | View</i>
                                    </button>
                                </td>
                                <td>
                                    <button class="btn btn-warning edit-btn" data-bs-toggle="modal" data-bs-target="#studentEditModal"
                                    data-student-id="{{ student.id }}" data-student-firstname="{{ student.firstName }}"
                                    data-student-lastname="{{ student.lastName }}" data-student-course="{{ student.course }}"
                                    data-student-year="{{ student.year }}" data-student-gender="{{ student.gender }}" data-student-photo="{{ student.photoUrl }}">
                                    <i class="fa fa-pencil"></i> | Edit</button>
                                    <button class="btn btn-danger delete-btn" data-student-id="{{ student.id }}" data-student-photo="{{ student.photoUrl }}"><i class="fa fa-trash"></i> | Delete</button>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="7">No results found</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>    
</section>

<script>
    var deleteUrl = "{{ url_for('student_bp.delete') }}";
    var searchUrl = "{{ url_for('student_bp.search') }}";
    var csrfToken = "{{ csrf_token() }}";
</script>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="{{ url_for('static', filename='js/student.js') }}"></script>

<!-- Student Modal here -->
{% include 'modal/add/student-m.html' %}
{% include 'modal/edit/student-me.html' %}
{% include 'modal/photo/student.html' %}

{% endblock %}