app/routes/college.py
from flask import Blueprint, flash
from app.model.college_model import query_database, submit_form, edit_form, delete_form, search_form
from app.wtform.form import CollegeForm
from flask import render_template, request, redirect#, jsonify, url_for
#from flask import current_app as app

college_bp = Blueprint(
    "college_bp",
    __name__,
)

@college_bp.route('/')
def college():
    data = query_database()

    # Print the data for debugging purposes
    print("Data from query:", data)

    form = CollegeForm()
    return render_template('table/college.html', data=data, form=form)

@college_bp.route('/add', methods=['POST'])
def add():
    if request.method == 'POST':
        try:
            # Call the insert function in college_model
            submit_form()

            # Flash a success message
            # flash('Added successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Add failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@college_bp.route('/update', methods=['POST'])
def update():
    if request.method == 'POST':
        try:
            # Call the update function in college_model
            edit_form()

            # Flash a success message
            # flash('Updated successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Update failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@college_bp.route('/delete', methods=['POST'])
def delete():
    if request.method == 'POST':
        try:
            # Call the delete function in college_model
            delete_form()

            # Flash a success message
            # flash('Deleted successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Delete failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@college_bp.route('/search', methods=['POST'])
def search():
    search_query = request.form.get('search-query', '').lower()

    print(f"Received search query: {search_query} for table tblcollege")

    # Perform search logic based on the query
    search_results = search_form(search_query)

    #print(search_results)
    print(f"Final search results: {search_results}")
    
    return render_template('form/search/college-fs.html', results=search_results, form=CollegeForm())

app/routes/course.py
from flask import Blueprint, flash
from app.model.course_model import query_database, submit_form, edit_form, delete_form, search_form
from app.wtform.form import CourseForm
from flask import render_template, request, redirect#, jsonify, url_for

course_bp = Blueprint(
    "course_bp",
    __name__,
)

@course_bp.route('/')
def course():
    data = query_database()

    # Print the data for debugging purposes
    print("Data from query:", data)

    form = CourseForm()
    return render_template('table/course.html', data=data, form=form)

@course_bp.route('/add', methods=['POST'])
def add():
    if request.method == 'POST':
        try:
            # Call the insert function in course_model
            submit_form()

            # Flash a success message
            # flash('Added successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Add failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@course_bp.route('/update', methods=['POST'])
def update():
    if request.method == 'POST':
        try:
            # Call the update function in course_model
            edit_form()

            # Flash a success message
            # flash('Updated successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Update failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@course_bp.route('/delete', methods=['POST'])
def delete():
    if request.method == 'POST':
        try:
            # Call the delete function in course_model
            delete_form()

            # Flash a success message
            # flash('Deleted successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Delete failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@course_bp.route('/search', methods=['POST'])
def search():
    search_query = request.form.get('search-query', '').lower()

    print(f"Received search query: {search_query} for table tblcourse")

    # Perform search logic based on the query
    search_results = search_form(search_query)

    #print(search_results)
    print(f"Final search results: {search_results}")
    
    return render_template('form/search/course-fs.html', results=search_results, form=CourseForm())

app/routes/main.py
from flask import Blueprint, flash
from flask import render_template, request, redirect
from app.model.student_model import submit_form, query_database
from app.wtform.form import StudentForm

from app.model.course_model import query_database as query_course

main_bp = Blueprint(
    "main_bp",
    __name__,
)

@main_bp.route('/')
def home():
    # form = StudentForm()
    # return render_template('home.html', form=form)
    data = query_database()

    # Print the data for debugging purposes
    print("Data from query:", data)

    form = StudentForm()
    courses = query_course() #get courses available in course table
    return render_template('table/student.html', data=data, form=form, courses=courses)

# @main_bp.route('/submit', methods=['POST'])
# def submit():
#     if request.method == 'POST':
#         try:
#             submit_form()

#             # Flash a success message
#             flash('Submitted successfully!', 'success')
#         except Exception as e:
#             # Flash an error message
#             flash(f'Submission failed: {str(e)}', 'danger')
    
#     return redirect(request.referrer)

app/routes/student.py
from flask import Blueprint, flash
from app.model.student_model import query_database, submit_form, edit_form, delete_form, search_form
from app.model.course_model import query_database as query_course
from app.wtform.form import StudentForm
from flask import render_template, request, redirect
import re

from cloudinary.uploader import upload, destroy
from app.model.util import public_id

student_bp = Blueprint(
    "student_bp",
    __name__,
)

@student_bp.route('/')
def student():
    data = query_database()

    # Print the data for debugging purposes
    print("Data from query:", data)

    form = StudentForm()
    courses = query_course() #get courses available in course table
    return render_template('table/student.html', data=data, form=form, courses=courses)

@student_bp.route('/add', methods=['POST'])
def add():
    if request.method == 'POST':
        id = request.form['id']
        photo = request.files['photo']
        #Check if ID correct format
        if not re.match(r'\d{4}-\d{4}', id):
            flash("Incorrect format.", 'danger')
            return redirect(request.referrer)
        try:
            if photo:
                upload_result = upload(photo, folder="ssis", resource_type='image')
                secure_url = upload_result['secure_url']
            else:
                secure_url = None
            # Call the insert function in student_model
            submit_form(secure_url)

            # Flash a success message
            # flash('Added successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Add failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

from flask import make_response

@student_bp.route('/update', methods=['POST'])
def update():
    if request.method == 'POST':
        currentPhoto = request.form.get('currentStudentPhotoUrl')
        newPhoto = request.files['studentPhoto']
        
        print("Current Photo: ",currentPhoto)
        print("New Photo :",newPhoto)
        try:
            # Upload new photo to cloudinary
            if newPhoto:
                upload_result = upload(newPhoto, folder="ssis", resource_type='image')
                secure_url = upload_result['secure_url']

                # flash(f"Uploaded new photo: {secure_url}", 'info')
                # Delete old photo from cloudinary
                if currentPhoto:
                    try:
                        # Extract public ID from the photo URL
                        public_id_val = public_id(currentPhoto)

                        # Delete the photo using its public ID
                        result = destroy("ssis/" + public_id_val)

                        # Check the deletion result
                        # if result.get("result") == "ok":
                        #     # Flash a success message
                        #     # flash('Updated successfully!', 'success')
                        # else:
                        #     # Flash an error message
                        #     flash(f"Error deleting old photo: {result.get('result')}", 'danger')
                    except Exception as e:
                        flash(f"Error deleting old photo: {str(e)}", 'danger')

                    # Call the update function in student_model
                    edit_form(secure_url)
                else:
                    # Call the update function in student_model
                    edit_form(secure_url)
                    # Flash a success message
                    # flash('Updated successfully!', 'success')
            else:
                secure_url = None

                # Call the update function in student_model
                edit_form(secure_url)
                # Flash a success message
                # flash('Updated successfully! No new photo.', 'success')

        except Exception as e:
            # Flash an error message
            flash(f'Update failed: {str(e)}', 'danger')
    
    # return jsonify({'success': False, 'error': 'Invalid request. Missing required data.'})
    return redirect(request.referrer)

@student_bp.route('/delete', methods=['POST'])
def delete():
    if request.method == 'POST':
        # Retrieve photo url
        photo = request.form.get('photoUrl')
        print("Photo: ",photo)
        try:
            # Delete old photo from cloudinary
            if photo:
                try:
                    # Extract public ID from the photo URL
                    public_id_val = public_id(photo)

                    # Delete the photo using its public ID
                    result = destroy("ssis/" + public_id_val)

                    # Check the deletion result
                    # if result.get("result") == "ok":
                    #     # Flash a success message
                    #     flash('Updated successfully!', 'success')
                    # else:
                    #     # Flash an error message
                    #     flash(f"Error deleting old photo: {result.get('result')}", 'danger')
                except Exception as e:
                    flash(f"Error deleting old photo: {str(e)}", 'danger')

                # Call the delete function in student_model
                delete_form()
            else:
                # Call the delete function in student_model
                delete_form()
                # Flash a success message
                # flash('Deleted successfully!', 'success')
        except Exception as e:
            # Flash an error message
            flash(f'Delete failed: {str(e)}', 'danger')
    
    return redirect(request.referrer)

@student_bp.route('/search', methods=['POST'])
def search():
    search_query = request.form.get('search-query', '').lower()

    print(f"Received search query: {search_query} for table tblstudent")

    # Perform search logic based on the query
    search_results = search_form(search_query)

    #print(search_results)
    print(f"Final search results: {search_results}")
    
    return render_template('form/search/student-fs.html', results=search_results, form=StudentForm())

app/templates/home.html
{% extends 'layout.html' %}
{% block content %}
<br>
<section>
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
{% endif %}
{% endwith %}

<h2 class="mt-2 mb-1 ml-2 mr-2 d-flex justify-content-between align-items-center">Student Information Form
    <a class="btn btn-success" href="{{ url_for('student_bp.student') }}">
        <i class="fa fa-eye"></i> View
    </a>
</h2>

<hr>

<div class="card ml-2 mr-2">
    <div class="card-body"> 
        <form method="POST" action="{{ url_for('main_bp.submit') }}">
            {{ form.hidden_tag() }}
    
            <div class="mb-3 ml-2 mr-2">
                <label for="{{ form.id.id }}" class="form-label">Student ID:</label>
                {{ form.id(class="form-control", placeholder="YYYY-NNNN") }}
            </div>
    
            <div class="mb-3 ml-2 mr-2">
                <label for="{{ form.firstname.id }}" class="form-label">First Name:</label>
                {{ form.firstname(class="form-control") }}
            </div>
    
            <div class="mb-3 ml-2 mr-2">
                <label for="{{ form.lastname.id }}" class="form-label">Last Name:</label>
                {{ form.lastname(class="form-control") }}
            </div>
    
            <div class="mb-3 ml-2 mr-2">
                <label for="{{ form.gender.id }}" class="form-label">Gender:</label>
                {{ form.gender(class="form-select w-auto") }}
            </div>
    
            <div class="mb-3 ml-2 mr-2">
                <label for="{{ form.college.id }}" class="form-label">College:</label>
                {{ form.college(class="form-select w-auto") }}
            </div>
    
            <div class="mb-3 ml-2 mr-2">
                <label for="{{ form.course.id }}" class="form-label">Course:</label>
                {{ form.course(class="form-select w-auto") }}
            </div>
    
            <div class="mb-3 ml-2 mr-2">
                <label for="{{ form.year.id }}" class="form-label">Year:</label>
                {{ form.year(class="form-select w-auto") }}
            </div>
            
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary mr-2"><i class="fa fa-paper-plane-o"></i> | Submit</button>
            </div>
        </form>
    </div>
</div>

</section>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    // Define a dictionary of college-course mappings
    var courseChoices = {
        'College of Engineering': ['','Bachelor of Science in Metallurgical Engineering',
                'Bachelor of Science in Computer Engineering', 
                'Bachelor of Science in Electronics and Communication Engineering', 
                'Bachelor of Science in Mechanical Engineering', 
                'Bachelor of Science in Chemical Engineering', 'Bachelor of Science in Civil Engineering',
                'Bachelor of Science in Industrial Automation and Mechatronics',
                'Bachelor of Science in Ceramics Engineering', 'Bachelor of Science in Mining Engineering',
                'Bachelor of Science in Electrical Engineering', 'Bachelor of Science in Environmental Engineering'],
        'College of Arts and Social Sciences': ['','Bachelor of Arts in English Language Studies', 
                'Bachelor of Arts in Literary and Culture Studies', 
                'Bachelor of Arts in Filipino', 'Bachelor of Arts in History',
                'Bachelor of Arts in Panitikan', 'Bachelor of Arts in Political Science',
                'Bachelor of Arts in Psychology','Bachelor of Arts in Sociology',
                'Bachelor of Science in Philosophy', 'Bachelor of Science in Psychology'],
        'College of Economics and Business Administration': ['','Bachelor of Science in Accountancy', 'Bachelor of Science in Economics',
                'Bachelor of Science in Business Administration major in Business Economics',
                'Bachelor of Science in Business Administration major in Marketing Management',
                'Bachelor of Science in Entrepreneurship', 'Bachelor of Science in Hospitality Management'],
        'College of Education': ['','Bachelor of Elementary Education – Language Education', 
                'Bachelor of Elementary Education – Science and Mathematics', 
                'Bachelor of Secondary Education – Biology', 'Bachelor of Secondary Education – Chemistry',
                'Bachelor of Secondary Education – Physics', 'Bachelor of Secondary Education – Mathematics',
                'Bachelor of Physical Education','Bachelor of Technology and Livelihood Education major in Home Economics',
                'Bachelor of Technology and Livelihood Education major in Industrial Arts',
                'Bachelor of Technical-Vocational Teacher Education major in Drafting Technology'],
        'College of Health Sciences': ['','Bachelor of Science in Nursing'],
        'College of Science and Mathematics': ['','Bachelor of Science in Physics', 'Bachelor of Science in Chemistry', 
                'Bachelor of Science in Biology', 'Bachelor of Science in Statistics',
                'Bachelor of Science in Mathematics'],
        'College of Computer Studies': ['','Bachelor of Science in Computer Science',
                'Bachelor of Science in Computer Application' ,
                'Bachelor of Science in Information Technology', 'Bachelor of Science in Information System']
    };

    // Function to update the course dropdown based on the selected college
    function updateCourseDropdown() {
        var selectedCollege = $('#{{ form.college.id }}').val();
        var courses = courseChoices[selectedCollege] || [];
        
        // Clear existing options
        $('#{{ form.course.id }}').empty();

        // Add new options
        $.each(courses, function(index, course) {
            $('#{{ form.course.id }}').append('<option value="' + course + '">' + course + '</option>');
        });
    }

    // Attach the function to the change event of the college dropdown
    $('#{{ form.college.id }}').change(function() {
        updateCourseDropdown();
    });

    // Initial update when the page loads
    updateCourseDropdown();

    $(document).ready(function(){
    // Set a timeout to fade out the alert after 3 seconds (adjust the duration as needed)
    setTimeout(function(){
        $('.alert').fadeOut('slow');
    }, 3000);
});
</script>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">

    <!-- Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    {% if title %}
        <title>SSIS - {{ title }}</title>
    {% else %}
        <title>SSIS</title>
    {% endif %}
</head>
<body>
    <header>
        <nav class="navbar navbar-light" style="background-color:black;color: white; font-family: 'Courier New', Courier, monospace;">
            <div class="container-fluid">
                <a class="navbar-brand" style="color: #5b5858; margin-left: 1.5rem;"><i class="fa fa-file-text"></i> SSIS</a>
                <!-- <a class="nav-link" style="color: white;" href="{{ url_for('main_bp.home') }}"><i class="fa fa-home"></i></a> -->
                <a class="nav-link" style="color: white;" href="{{ url_for('student_bp.student') }}"
                onmouseover="this.style.color='rgba(255, 0, 255, 0.8 )'" onmouseout="this.style.color='white'"><i class="fa fa-user"></i> Student</a>
                <a class="nav-link" style="color: white;" href="{{ url_for('course_bp.course') }}"
                onmouseover="this.style.color='rgba(255, 0, 255, 0.8)'" onmouseout="this.style.color='white'"><i class="fa fa-book"></i> Course</a>
                <a class="nav-link" style="color: white;" href="{{ url_for('college_bp.college') }}"
                onmouseover="this.style.color='rgba(255, 0, 255, 0.8)'" onmouseout="this.style.color='white'"><i class="fa fa-university"></i> College</a>
                <a class="nav-link disabled" style="font-size: small; font-family: sans-serif; margin-right: 0.5rem;" href="#" tabindex="-1" aria-disabled="true">Simple Student Information System</a>
            </div>
          </nav>
    </header>

    <div class="container-fluid">

        {% block content %}
        {% endblock %}

    </div>

    <!-- Optional JavaScript -->
    <!-- Popper first then Bootstrap JS for Bootstrap 5 -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>